#ifndef __BITMAPS_H__
#define __BITMAPS_H__

const unsigned char bitmap_96x2_bike[];
const unsigned char bitmap_antena[];
const unsigned char bitmap_antena_no[];
const unsigned char bitmap_n_0[];
const unsigned char bitmap_n_1[];
const unsigned char bitmap_n_2[];
const unsigned char bitmap_n_3[];
const unsigned char bitmap_n_4[];
const unsigned char bitmap_n_5[];
const unsigned char bitmap_n_6[];
const unsigned char bitmap_n_7[];
const unsigned char bitmap_n_8[];
const unsigned char bitmap_n_9[];
const unsigned char bitmap_x4_0[];
const unsigned char bitmap_x4_1[];
const unsigned char bitmap_x4_100m[];
const unsigned char bitmap_x4_2[];
const unsigned char bitmap_x4_3[];
const unsigned char bitmap_x4_4[];
const unsigned char bitmap_x4_5[];
const unsigned char bitmap_x4_6[];
const unsigned char bitmap_x4_7[];
const unsigned char bitmap_x4_8[];
const unsigned char bitmap_x4_9[];
const unsigned char bitmap_x4_accident[];
const unsigned char bitmap_x4_back[];
const unsigned char bitmap_x4_bike[];
const unsigned char bitmap_x4_course[];
const unsigned char bitmap_x4_crash[];
const unsigned char bitmap_x4_curve[];
const unsigned char bitmap_x4_downhill[];
const unsigned char bitmap_x4_drop[];
const unsigned char bitmap_x4_flat_tire[];
const unsigned char bitmap_x4_km[];
const unsigned char bitmap_x4_logo[];
const unsigned char bitmap_x4_logo_2[];
const unsigned char bitmap_x4_logo_3[];
const unsigned char bitmap_x4_meal[];
const unsigned char bitmap_x4_nocon[];
const unsigned char bitmap_x4_nogps[];
const unsigned char bitmap_x4_rest[];
const unsigned char bitmap_x4_rest_text[];
const unsigned char bitmap_x4_start[];
const unsigned char bitmap_x4_uphill[];
const unsigned char bitmap_x4_waiting[];
#endif //__BITMAPS_H__
